# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "next"
  command = "npm run dev"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "www.stockwise.app"

 # Although there is also this redirect rule in "/public/_redirects", this must be here for local redirects.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"


  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
